apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dbo2uswss-dotnet-basic
  janus-idp.io/tekton: dbo2uswss-dotnet-basic
  backstage.io/kubernetes-id: dbo2uswss-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dbo2uswss-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
