apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: dbo2uswss-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/dbo2uswss-dotnet-basic-gitops